### ISSUE TITLE
Connecting to localhost when cluster passed

### ISSUE THREAD

**Issue by integrii** [antirez/redis-rb-cluster#3]
It looks like my servers are being forgotten and then to localhost somewhere.

I am running this program below which simply connects to two clusters, reads keys from a text file and copies them from one cluster to the other.

However, I keep getting the following error indicating that it can not connect to localhost.  Any ideas?
```
[eric@bastion2 redis-rb-cluster]$ ./migrate.rb 
./cluster.rb:192:in `get_random_connection': Can't reach a single startup node. Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED) (RuntimeError)
	from ./cluster.rb:201:in `get_connection_by_slot'
	from ./cluster.rb:235:in `send_cluster_command'
	from ./cluster.rb:275:in `method_missing'
	from ./migrate.rb:50
	from ./migrate.rb:46:in `each'
	from ./migrate.rb:46
```

```ruby
require './cluster.rb'

# call out our file that lists the keys to migrate
keyListFile="keyList.txt"

sourceHosts = [
    {'host' => '172.31.37.165', 'port' => 6379},
    {'host' => '172.31.37.162', 'port' => 6379},
    {'host' => '172.31.37.164', 'port' => 6379},
    {'host' => '172.31.37.169', 'port' => 6379},
    {'host' => '172.31.37.170', 'port' => 6379},
    {'host' => '172.31.37.168', 'port' => 6379}
]
destinationHosts = [
    {'host' => '172.31.34.231', 'port' => 6379},
    {'host' => '172.31.34.228', 'port' => 6379},
    {'host' => '172.31.34.227', 'port' => 6379},
    {'host' => '172.31.34.230', 'port' => 6379},
    {'host' => '172.31.34.229', 'port' => 6379},
    {'host' => '172.31.34.226', 'port' => 6379}
]



# Open redis cluster connections
max_cached_connections = 2
sourceCluster = RedisCluster.new(sourceHosts,max_cached_connections)
destinationCluster = RedisCluster.new(destinationHosts,max_cached_connections)


# Read in our key list
File.open(keyListFile).each do |key|
        print "Migrating key: " + key

        # Fetch key TTL
        keyTtl = sourceCluster.pttl(key)

        # Copy key content
        keyContent = sourceCluster.get(key)
        destinationCluster.set(key,keyContent)

        # Set key TTL
        destinationCluster.ttl(key,keyTtl)
end

```

**Comment by Hulva** [comment]
Have you work it out? @integrii

**Comment by integrii** [comment]
Oh man. This was so long ago. No idea now. Thanks for checking though. 

Closing this.
